export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const REMOVE_PROFILE = "REMOVE_PROFILE";
export const SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE";
export const ADD_PROFILE = "ADD_PROFILE";
export const LOADING = "LOADING";
export const ADD_MATCH = "ADD_MATCH";
export const REMOVE_MATCH = "REMOVE_MATCH";
export const UPDATE_MATCHES = "UPDATE_MATCHES";